server:
    domain: 'example.com'
    auth: 'passkey for authentication'
    port: 80

db:
    url: 'mongodb+srv://<username>:<password>@production.lskrx.mongodb.net/<database>?retryWrites=true&w=majority'
    database: '<database>'
    collection: '<collection>'
