server:
    domain: 'log.zytekaron.com'
    port: 1350

db:
    url: 'mongodb+srv://service_key:xxRmxErnkq3pqfEN@production.lskrx.mongodb.net/zytekaron?retryWrites=true&w=majority'
    database: 'zytekaron'
    collection: 'logs'
