name: AutoDeployer

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the logging service
        run: |
          echo Making request to deploy.zytekaron.com/logbyte/deploy
          curl -H "Authorization: ${{ secrets.AUTH }}" https://deploy.zytekaron.com/logbyte/deploy
